name: CI with Bazel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_sql:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel
    - name: Setup bazel
      uses: jwlawson/actions-setup-bazel@v1
      with:
        bazel-version: '4.0.0'
    - name: test all
      run: bazel test  //...
    
